version: '3.8'

services:
  webapi:
    image: 'bartlomiejpierog/garnek-webapi:latest'
    container_name: webapi
    build: 
      context: .
      dockerfile: ./docker/webapi/Dockerfile
    ports:
      - "8080:8080"
  frontend:
    image: 'bartlomiejpierog/front-end-webapi:latest'
    container_name: frontend
    build: 
      context: ./Frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - '9000:80'
