// <auto-generated />
using System;
using Garnek.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garnek.WebAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221127141633_PolishLabelAdded")]
    partial class PolishLabelAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Garnek.Model.DatabaseModels.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolishLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8e14638-59c8-46d8-8aa7-e3f0aa7b86f6"),
                            CreatedAt = new DateTime(2022, 11, 27, 14, 16, 33, 586, DateTimeKind.Utc).AddTicks(5630),
                            Name = "People",
                            PolishLabel = "Osoby 💆🏼‍"
                        },
                        new
                        {
                            Id = new Guid("f64206c8-4dcb-4415-89cd-367571420fb5"),
                            CreatedAt = new DateTime(2022, 11, 27, 14, 16, 33, 586, DateTimeKind.Utc).AddTicks(5720),
                            Name = "Places",
                            PolishLabel = "Miejsca 🌁"
                        },
                        new
                        {
                            Id = new Guid("0416457b-a013-491b-b38c-57b6699d4990"),
                            CreatedAt = new DateTime(2022, 11, 27, 14, 16, 33, 586, DateTimeKind.Utc).AddTicks(5730),
                            Name = "Things",
                            PolishLabel = "Rzeczy 🎸"
                        });
                });

            modelBuilder.Entity("Garnek.Model.DatabaseModels.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Garnek.Model.DatabaseModels.Phrase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Phrases");
                });

            modelBuilder.Entity("Garnek.Model.DatabaseModels.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Garnek.Model.DatabaseModels.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Garnek.Model.DatabaseModels.Phrase", b =>
                {
                    b.HasOne("Garnek.Model.DatabaseModels.Category", "Category")
                        .WithMany("Phrases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Garnek.Model.DatabaseModels.User", "User")
                        .WithMany("Phrases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Garnek.Model.DatabaseModels.User", b =>
                {
                    b.HasOne("Garnek.Model.DatabaseModels.Game", "Game")
                        .WithMany("Users")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Garnek.Model.DatabaseModels.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Game");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Garnek.Model.DatabaseModels.Category", b =>
                {
                    b.Navigation("Phrases");
                });

            modelBuilder.Entity("Garnek.Model.DatabaseModels.Game", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Garnek.Model.DatabaseModels.Team", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Garnek.Model.DatabaseModels.User", b =>
                {
                    b.Navigation("Phrases");
                });
#pragma warning restore 612, 618
        }
    }
}
